[package]
name = "amazon-ssm-agent"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[[package.metadata.build-package.external-files]]
url = "https://github.com/aws/amazon-ssm-agent/archive/3.3.40.0/amazon-ssm-agent-3.3.40.0.tar.gz"
sha512 = "3397dc2604b22f3457c43a0efa3ccadc8d4b5db4036a93413138bf00d0d54c052dfe6d657b21097df94300c7cfb6f8b5b4bd2ddae228957d96c85e08814a9ec5"

[build-dependencies]
glibc = { path = "../glibc" }
