[package]
name = "libglib"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://download.gnome.org/sources/glib"

[[package.metadata.build-package.external-files]]
url = "https://download.gnome.org/sources/glib/2.78/glib-2.78.2.tar.xz"
sha512 = "d09d25977c2121e68e6215c29d672330b88b4d11e1c34b81b658225ae3e63226c64ce91d3093b9718bef62be0d549b3e46f0177560fb0585c5bfb21de45d1c83"

[build-dependencies]
glibc = { path = "../glibc" }
libffi = { path = "../libffi" }
libpcre = { path = "../libpcre" }
libselinux = { path = "../libselinux" }
libz = { path = "../libz" }
util-linux = { path = "../util-linux" }
