[package]
name = "systemd"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/systemd/systemd-stable/releases"
package-features = ["unified-cgroup-hierarchy"]

[[package.metadata.build-package.external-files]]
url = "https://github.com/systemd/systemd-stable/archive/v252.18/systemd-stable-252.18.tar.gz"
sha512 = "0c8ec1aceb43a74693876e27b84df0973e879fca96960c32d28f365703ad6b2c193fce2038c169f0ad6f31e75bca19d880c6106d7737ce26e165f427957ba339"

[build-dependencies]
glibc = { path = "../glibc" }
kmod = { path = "../kmod" }
libacl = { path = "../libacl" }
libattr = { path = "../libattr" }
libcap = { path = "../libcap" }
libseccomp = { path = "../libseccomp" }
libselinux = { path = "../libselinux" }
libxcrypt = { path = "../libxcrypt" }
util-linux = { path = "../util-linux" }
